# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    admin_email: manager@example.com
    lolcat_remplacements:
        chat: ðŸ±
        Socrate: ðŸ‘¨
        mortel: (âœ–â•­â•®âœ–)
services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'

    AppBundle\Service\NotificationAffichageCitation:
        arguments:
            $adminEmail: '%admin_email%'
            
    AppBundle\Twig\AppExtension:
        arguments:
            $remplacements: '%lolcat_remplacements%'
            
    AppBundle\Beta\BetaListener:
        arguments:
            - '@AppBundle\Beta\BetaHTMLAdder'
            - '2017-08-31'
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }

    AppBundle\EventListener\LoggerOnLivreVu:
        #arguments:         ------------> NON NECESSAIRE GRACE A L'AUTOWIRE
        #    - "@logger"                  de symfony Ã  partir de la version3.3
        tags:
            - { name: kernel.event_listener, event: app.livre.vu, method: process }
            
    AppBundle\EventListener\MailOnLivreVu:
        tags:
            - { name: kernel.event_listener, event: app.livre.vu, method: envoiMail }

    AppBundle\EventListener\LivreSubscriber:
        tags:
            - { name: doctrine.event_subscriber }
    
    AppBundle\DataCollector\RequestCollector:
        tags:
            -
                name:     data_collector
                template: 'data_collector/template.html.twig'
                # must match the value returned by the getName() method
                id:       'app.request_collector'
                # optional priority
                # priority: 300
        public: false
